name: Foundry CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$HOME/.foundry/bin:$PATH"
          foundryup

      - name: Build
        run: forge build

      - name: Test
        run: forge test -vv