name: Foundry CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$HOME/.foundry/bin:$PATH"
          ~/.foundry/bin/foundryup

      - name: Verify Foundry
        run: ~/.foundry/bin/forge --version

      - name: Build
        run: ~/.foundry/bin/forge build

      - name: Test
        run: ~/.foundry/bin/forge test -vv
